spring:
 datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/1369
    username: root
    password:
 
spring.jpa:
  hibernate.ddl-auto: update
  show-sql: true
  


  